buildscript {
    ext {
        grailsVersion = project.grailsVersion
    }
    repositories {
        mavenLocal()
        maven { url "https://repo.grails.org/grails/core" }
    }
    dependencies {
        classpath "org.apache.grails:grails-gradle-plugins:$grailsVersion"
    }
}

version "0.1"
group "grails.bugsnag.plugin"

apply plugin: "eclipse"
apply plugin: "idea"
apply plugin: "org.apache.grails.gradle.grails-plugin"
//apply plugin: "org.apache.grails.gradle.grails-gsp"

ext {
    grailsVersion = project.grailsVersion
    gradleWrapperVersion = project.gradleWrapperVersion
}

repositories {
    mavenLocal()
    maven { url "https://repo.grails.org/grails/core" }
    mavenCentral()
}

//dependencyManagement {
//    imports {
//        mavenBom "org.grails:grails-bom:$grailsVersion"
//        mavenBom "org.springframework.boot:spring-boot-dependencies:$springBootVersion"
//    }
//    applyMavenExclusions true
//}
dependencies {
//    implementation "org.springframework.boot:spring-boot-starter-logging"
    implementation 'org.slf4j:slf4j-api:1.7.36'
    runtimeOnly 'ch.qos.logback:logback-classic:1.5.6'
    implementation "org.springframework.boot:spring-boot-autoconfigure"
    implementation "org.apache.grails:grails-core"
    implementation "org.springframework.boot:spring-boot-starter-actuator"
    implementation "org.springframework.boot:spring-boot-starter-tomcat"
    implementation "org.apache.grails:grails-dependencies-starter-web"
    implementation "org.apache.grails:grails-web-boot"
    implementation "org.apache.grails:grails-cache"
    implementation "org.apache.grails:grails-scaffolding"
    console "org.apache.grails:grails-console"
    implementation 'com.bugsnag:bugsnag:3.6.4'
    //implementation 'org.springframework:spring-test:6.0.2'
    compileOnly "org.apache.grails:grails-services"
    compileOnly "org.apache.grails:grails-domain-class"
//    testImplementation "org.apache.grails.testing:grails-testing-support-core"
//    testImplementation "org.apache.grails.plugins:geb"
    testRuntimeOnly 'org.seleniumhq.selenium:selenium-htmlunit-driver:2.52.0'
    testRuntimeOnly 'net.sourceforge.htmlunit:htmlunit:2.67.0'
}

task wrapper(type: Wrapper) {
    gradleVersion = gradleWrapperVersion
}
